# tasks file for helloworld
- name: Hello World!
  debug:
    msg: "こんぺこ～"

- name: add nginx user
  user:
    name: nginx

- name: install nginx
  apt:
    name: nginx
    state: latest
    update_cache: yes
    cache_valid_time: 3600

- name: start nginx service
  service:
    name: nginx
    enabled: yes

- name: put nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default

- name: change nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - restart nginx
